<a href="https://colab.research.google.com/github/bored-em/assignments/blob/main/Deliverable_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split


#Downloaded & Uploaded train.csv and test.csv  to session before running colab
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [14]:
train.describe()

       SeniorCitizen         tenure  MonthlyCharges   TotalCharges
count  594194.000000  594194.000000   594194.000000  594194.000000
mean        0.114102      36.577258       65.866223    2494.377057
std         0.317936      25.061922       31.067444    2353.916710
min         0.000000       1.000000       18.250000      18.800000
25%         0.000000      12.000000       29.900000     639.650000
50%         0.000000      35.000000       74.100000    1433.650000
75%         0.000000      62.000000       90.800000    4263.800000
max         1.000000      72.000000      118.750000    8684.800000

In [ ]:
train.head()

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,Male,0,Yes,Yes,29,Yes,No,DSL,Yes,...,Yes,Yes,No,No,One year,Yes,Mailed check,60.10,1653.85,No
1,1,Male,0,Yes,Yes,58,Yes,No,DSL,Yes,...,No,Yes,Yes,No,Two year,No,Credit card (automatic),69.50,3778.20,No
2,2,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.40,5841.35,No
3,3,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,70.70,Yes
4,4,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.45,70.45,Yes

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594194 entries, 0 to 594193
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                594194 non-null  int64
 1   gender            594194 non-null  object
 2   SeniorCitizen     594194 non-null  int64
 3   Partner           594194 non-null  object
 4   Dependents        594194 non-null  object
 5   tenure            594194 non-null  int64
 6   PhoneService      594194 non-null  object
 7   MultipleLines     594194 non-null  object
 8   InternetService   594194 non-null  object
 9   OnlineSecurity    594194 non-null  object
 10  OnlineBackup      594194 non-null  object
 11  DeviceProtection  594194 non-null  object
 12  TechSupport       594194 non-null  object
 13  StreamingTV       594194 non-null  object
 14  StreamingMovies   594194 non-null  object
 15  Contract          594194 non-null  object
 16  PaperlessBilling  594194 non-null  object
 17  PaymentMethod     594194 non-null  object
 18  MonthlyCharges    594194 non-null  float64
 19  TotalCharges      594194 non-null  float64
 20  Churn             594194 non-null  object
dtypes: float64(2), int64(3), object(16)
memory usage: 95.2+ MB

In [33]:
from sklearn.preprocessing import OrdinalEncoder

#id is not an important attribute for our model
#try to associate pattern to the id attribute
test_id = test['id']

train = train.drop('id', axis=1, errors='ignore')
test = test.drop('id', axis=1, errors='ignore')
x = train.drop('Churn', axis=1)
y = train['Churn']

#chapter 13 from handson-ml3
#used to encode a categorical feature
cat = x.select_dtypes(include='object').columns
encode = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
x[cat] = encode.fit_transform(x[cat])
test[cat] = encode.transform(test[cat])

#split data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [29]:
from sklearn.ensemble import RandomForestClassifier

#train the model
model = RandomForestClassifier(n_estimators=50, max_depth=10, n_jobs=-1, random_state=42)
model.fit(x_train, y_train)

RandomForestClassifier(max_depth=10, n_estimators=50, n_jobs=-1,
                       random_state=42)

In [30]:
from sklearn.metrics import roc_auc_score

#give the roc accuracy score
y_prob = model.predict_proba(x_test)[:, 1]
print('roc_auc_score: ', round(roc_auc_score(y_test, y_prob), 2))

roc_auc_score:  0.91

In [34]:
#test the model and create submission
test_prob = model.predict_proba(test)[:, 1]

submission = pd.DataFrame({'id': test_id, 'Churn': test_prob})
submission.to_csv('submission.csv', index=False)